#!/bin/sh
#
# get_libdsys_version
# Retrives versoin information from 'VERSION'
#
# Copyright (C) 2004, Gagarine Yaikhom
# Copyright (C) 2004, University of Edinburgh 
#
# $Id$
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

ver_file="$1"
options="$2"

if test "$ver_file" = ""; then
	options="-h"
else
#
# Get the version numbers from the version file.
#
	LIBDSYS_VER_MAJOR="`cat $ver_file | grep major | cut -d= -f2`"
	LIBDSYS_VER_MINOR="`cat $ver_file | grep minor | cut -d= -f2`"
	LIBDSYS_VER_RELEASE="`cat $ver_file | grep release | cut -d= -f2`"
	LIBDSYS_VER_ALPHA="`cat $ver_file | grep alpha | cut -d= -f2`"
	LIBDSYS_VER_BETA="`cat $ver_file | grep beta | cut -d= -f2`"

#
# Check if release is necessary.
#
	if test "$LIBDSYS_VER_RELEASE" != "0" -a "LIBDSYS_VER_RELEASE" != ""; then
		LIBDSYS_VER="$LIBDSYS_VER_MAJOR.$LIBDSYS_VER_MINOR.$LIBDSYS_VER_RELEASE"
    else
        LIBDSYS_VER="$LIBDSYS_VER_MAJOR.$LIBDSYS_VER_MINOR"
	fi

#
# Check if alpha or beta version.
#
    if test "`expr $LIBDSYS_VER_ALPHA \> 0`" = "1"; then
        LIBDSYS_VER="${LIBDSYS_VER}a$LIBDSYS_VER_ALPHA"
    elif test "`expr $LIBDSYS_VER_BETA \> 0`" = "1"; then
        LIBDSYS_VER="${LIBDSYS_VER}b$LIBDSYS_VER_BETA"
	fi

#
# If no options were provided, assume all.
#
	if test "$options" = ""; then
		options="-a"
	fi
fi

#
# Display the values.
#
case "$options" in
	-f)
		echo $LIBDSYS_VER
        ;;
	-M)
		echo $LIBDSYS_VER_MAJOR
        ;;
	-m)
		echo $LIBDSYS_VER_MINOR
        ;;
	-r)
		echo $LIBDSYS_VER_RELEASE
        ;;
	-a)
		echo $LIBDSYS_VER_ALPHA
        ;;
	-b)
		echo $LIBDSYS_VER_BETA
        ;;
	-h)
        	cat << EOF
$0 <VERSION_FILE> [<options>]
Options:
	-f Full version
	-M Major
   	-m Minor
	-r Release
	-a Alpha
	-b Beta
	-h Help message
EOF
esac

exit 0

# End of file
