/***************************************************************************
 *  Copyright  2004  Gagarine Yaikhom
 *  Copyright  2004  University of Edinburgh
 *  gyaikhom@gmail.com
 ****************************************************************************/

/*
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Library General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

/* Description:
 * Generates a pair of test matrices for inclusion in 'matrix_mul.c'.
 * The generated file is 'matrices.dat'.
 */
 
#include <stdio.h>
#include <stdlib.h>

static int generate_matrices(FILE *f, int nra, int nca, int nrb, int ncb,
    int seed, int limit);

int main(void)
{
    FILE *f;
    int nra, nca, nrb, ncb, seed, limit;
    
    if (!(f = fopen("matrices.dat", "w"))) {
        perror("Cannot create file");
        exit (1);
    }
    
    printf("Give dimensions of the matrices (row, column, row and column): ");
    scanf("%d %d %d %d", &nra, &nca, &nrb, &ncb);
    
    printf("Enter random seed: ");
    scanf("%d", &seed);
    
    printf("Enter element value limit: ");
    scanf("%d", &limit);
    
    generate_matrices(f, nra, nca, nrb, ncb, seed, limit);

    fclose(f);
    return 0;    
}

int
generate_matrices(FILE *f, int nra, int nca, int nrb, int ncb, int seed, int limit)
{
    int i;
    
    srandom(seed);
    fprintf(f, "/** Generated by \'matrix_gen\' as test data for inclusion\n"
        " * in \'matrix_mul.c\' during compilation.\n"
        " */\n");
    fprintf(f, "#define NROWS_A (%d)\n"
       "#define NCOLS_A (%d)\n"
       "int matrix_a[] = {", nra, nca);
    fprintf(f, "%ld", random()%limit);
    for (i = 1; i < nra*nca; i++)
        fprintf(f, ", %ld", random()%limit);
    fprintf(f, "};\n\n");
        
    fprintf(f, "#define NROWS_B (%d)\n"
        "#define NCOLS_B (%d)\n"
        "int matrix_b[] = {", nrb, ncb);
    fprintf(f, "%ld", random()%limit);
    for (i = 1; i < nrb*ncb; i++)
        fprintf(f, ", %ld", random()%limit);
    fprintf(f, "};\n");
    
    return 0;
}
